name: build
# This workflow is  triggered on pushes, pull requests to the repository.
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  version_in_development: v0.0.14

jobs:
  draft-release:
    name: Draft Release if develop branch
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.draft_release.outputs.upload_url }}  
      release_id: ${{ steps.draft_release.outputs.id }}  
    steps:
      - name: Create Release
        id: draft_release
        if: github.ref == 'refs/heads/develop' || github.head_ref == 'feature/status'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: tipi-build 
          repo: elfshaker
          commitish: main
          tag_name: ${{ env.version_in_development }}
          release_name: ${{ env.version_in_development }} ${{ github.sha }}
          draft: true
          prerelease: true 

  build-win:
    name: build-win
    runs-on: windows-2019
    needs: draft-release
    env:
      PreferredToolArchitecture: x64
    steps:
      - uses: actions/checkout@v2
      - name: install and build 
        run: |
          Invoke-WebRequest -Uri "https://win.rustup.rs/" -OutFile "rustup-init.exe"
          ./rustup-init.exe -q -y
          cargo  build --release --bin elfshaker
          cargo test
          Compress-Archive -Path .\target\release\elfshaker.exe -DestinationPath ./elfshaker-win.zip
      - uses: actions/upload-artifact@v3
        with:
          name: elfshaker_win_artifact
          path: ./elfshaker-win.zip
      - name: Upload elfshaker package
        id: upload-tipi-elfshaker-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.draft-release.outputs.upload_url}}
          asset_path: ./elfshaker-win.zip
          asset_name: elfshaker-win.zip
          asset_content_type: application/zip

  build-macos:
    name: build-macos
    runs-on: macos-latest
    needs: draft-release
    steps:
      - uses: actions/checkout@v2
      - name: install and build 
        run: |
          curl -fSL https://sh.rustup.rs --output ./sh.rustup.sh
          chmod +x ./sh.rustup.sh
          ./sh.rustup.sh -q -y
          cargo  build --release --bin elfshaker
          chmod +x ./target/release/elfshaker
          cargo test
          zip -j elfshaker-macos.zip ./target/release/elfshaker
      - uses: actions/upload-artifact@v3
        with:
          name: elfshaker_macos_artifact
          path: ./elfshaker.zip
      - name: Upload elfshaker package
        id: upload-tipi-elfshaker-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.draft-release.outputs.upload_url}}
          asset_path: ./elfshaker-macos.zip
          asset_name: elfshaker-macos.zip
          asset_content_type: application/zip

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container: 
      image: tipibuild/tipi-ubuntu-1604
    needs: draft-release
    steps:
      - uses: actions/checkout@v2
      - name: install and build 
        run: |
          sudo apt update && sudo apt install zip -y
          curl -fSL https://sh.rustup.rs --output ./sh.rustup.sh
          chmod +x ./sh.rustup.sh
          ./sh.rustup.sh -q -y --no-modify-path
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo  build --release --bin elfshaker
          chmod +x ./target/release/elfshaker
          cargo test
          zip -j elfshaker-linux.zip ./target/release/elfshaker
      - uses: actions/upload-artifact@v3
        with:
          name: elfshaker_linux_artifact
          path: ./elfshaker.zip
      - name: Upload elfshaker package
        id: upload-tipi-elfshaker-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.draft-release.outputs.upload_url}}
          asset_path: ./elfshaker-linux.zip
          asset_name: elfshaker-linux.zip
          asset_content_type: application/zip

